import js from '@eslint/js';
import globals from 'globals';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.es2021,
                ...globals.node,
                ...globals.jest,
                // Custom globals
                CookieUtils: 'readonly',
                DateUtils: 'readonly',
                CONFIG: 'readonly',
                CONSTANTS: 'readonly',
                TILE_DATA: 'readonly',
                TILE_TYPES: 'readonly',
                COMPACT_CHAR_TO_TILE: 'readonly',
                TILE_TO_COMPACT_CHAR: 'readonly',
                NUMERIC_ID_TO_SCORE: 'readonly',
                TILE_TO_NUMERIC: 'readonly',
                NUMERIC_TO_TILE: 'readonly',
                BLOCKING_NUMERIC_IDS: 'readonly',
                BLOCKING_TILES: 'readonly',
                isWallPlaceable: 'readonly',
                isBlockingTile: 'readonly',
                getTileScore: 'readonly',
                getNumericTileScore: 'readonly',
                getEligibleTileTypes: 'readonly',
                getTileType: 'readonly',
                isTileClickable: 'readonly',
                getTileAssets: 'readonly',
                getPawOverlay: 'readonly',
                Grid: 'readonly',
                Game: 'readonly',
                CloudSync: 'readonly',
                FIREBASE_CONFIG: 'readonly',
                firebase: 'readonly',
                MapGenerator: 'readonly',
                MapValidator: 'readonly',
                MILPSolver: 'readonly',
                PathfindingUtils: 'readonly',
                getRandomWord: 'readonly',
                WORD_LIST: 'readonly',
                updateMapInfo: 'readonly',
                SignatureUtils: 'readonly',
            },
        },
        rules: {
            'indent': ['error', 4],
            'linebreak-style': ['error', 'unix'],
            'quotes': ['error', 'single', { avoidEscape: true }],
            'semi': ['error', 'always'],
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
        },
    },
];
